set -sg escape-time 10
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Windows and panes start at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# New windows open in current path
bind c new-window -c "#{pane_current_path}"

set-window-option -g mode-keys vi
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g focus-events on
set -g status-interval 5

# Dracula theme
set -g status-style "bg=#1e1f29,fg=#f8f8f2"
set -g window-status-current-style "bg=#44475a,fg=#ff79c6"
set -g window-status-style "bg=#282a36,fg=#6272a4"
set -g pane-border-style "fg=#44475a"
set -g pane-active-border-style "fg=#bd93f9"
set -g message-style "bg=#44475a,fg=#f8f8f2"
set -g message-command-style "bg=#44475a,fg=#f8f8f2"
set -g mode-style "bg=#ffb86c,fg=#282a36"
set -g status-right "#[fg=#6272a4]%Y-%m-%d %H:%M #[fg=#bd93f9]⸨ #H ⸩"
set -g status-right-length 40
set -g status-justify centre

setw -g monitor-activity on
set -g visual-activity off

set -g renumber-windows on
set -g history-limit 50000
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.tmux.conf \; display "Reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set -g mouse on
set-option -g default-shell /usr/bin/fish

# Floating windows (Popups)
bind g display-popup -d '#{pane_current_path}' -w 80% -h 80% -E 'lazygit'
bind H display-popup -w 80% -h 80% -E 'htop'
bind S display-popup -d '#{pane_current_path}' -w 80% -h 80% -E
